union isfuzzy=true
(
    CrowdStrikeAlerts
    | summarize Records = count()
    | extend Source = "CrowdStrike"
),
(
    PaloAlto
    | summarize Records = count()
    | extend Source = "Palo Alto"
),
(
    OktaV2
    | summarize Records = count()
    | extend Source = "Okta"
),
(
    AWSCloudTrail
    | summarize Records = count()
    | extend Source = "AWS CloudTrail"
)
| project Source, Records
| order by Source asc
